image: docker:git
services:
  - docker:dind

stages:
  - test
  - release

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com 

tests:
  image: node:10.4-jessie
  stage: test
  script:
   - npm install
   - npm test

build_image:
  stage: release
  script:
    - docker build -t registry.example.com/johannessarpola/kyllikkibot.
    - docker run registry.example.com/johannessarpola/kyllikkibot/script/to/run/tests
    - docker push registry.example.com/johannessarpola/kyllikkibot:latest
  only:
    - master
