stages:
  - test
  - release
    
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/

tests:
  image: node:10.4-jessie
  stage: test
  script:
   - npm install
   - npm test

build_image:
  image: docker:git
  services:
    - docker:dind
  stage: release
  when: manual
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com 
    - docker build -t registry.gitlab.com/johannessarpola/kyllikkibot .
    - docker push registry.gitlab.com/johannessarpola/kyllikkibot:latest
  only:
    - master
