stages:
  - test
  - release  

tests:
  image: node:10.4-jessie
  stage: test
  script:
   - npm install
   - npm test

build_image:
  image: docker:git
  services:
    - docker:dind
  stage: release
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com 
    - docker build -t registry.example.com/johannessarpola/kyllikkibot .
    - docker run registry.example.com/johannessarpola/kyllikkibot/script/to/run/tests
    - docker push registry.example.com/johannessarpola/kyllikkibot:latest
  only:
    - master
